name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 6,18 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Install pup
      run: go get github.com/ericchiang/pup
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl 'https://njdg.ecourts.gov.in/njdgnew/index.php' | ~/go/bin/pup '.counter text{}' | xargs | tr -s [[:space:]] \\n | head -6 > cases.txt
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push -f
